FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json  package-lock.json turbo.json tsconfig.json ./ 

COPY app ./apps
COPY packages ./packages

RUN npm install
Run npm run db:generate
RUN npm run build

CMD ["npm", "run", "s"]